name: opendata
channels:
  - defaults
  - conda-forge
dependencies:
  - bokeh
  - click
  - dask
  - google-auth
  - google-cloud-core
  - google-cloud-bigquery
  - google-cloud-storage
  - lxml
  - nomkl
  - numpy
  - pandas >=1.0.0
  - pandas-gbq
  - pip
  - prefect[all_extras]
  - pip:
      - simpy
      - xmltodict
  - python >=3.8.0 # using dataclasess and zipfile.Path
  - pyyaml
  - requests
  - scikit-learn
  - scipy
  - sqlalchemy

  # packages for development, no separate dev option in conda
  - black
  - flake8
  - ipykernel
  - ipython
  - pdoc3
  - pytest
